alter table public.players drop constraint if exists chk_players_birth_date_iso;
alter table public.players drop constraint if exists chk_players_joined_date_iso;
alter table public.subscriptions drop constraint if exists chk_subscriptions_start_date_iso;
alter table public.subscriptions drop constraint if exists chk_subscriptions_end_date_iso;
alter table public.subscriptions drop constraint if exists chk_subscriptions_paid_at_format;
alter table public.trainings drop constraint if exists chk_trainings_session_date_iso;
alter table public.transactions drop constraint if exists chk_transactions_transaction_date_iso;
alter table public.players alter column birth_date drop default;
alter table public.players alter column joined_date drop default;
alter table public.subscriptions alter column start_date drop default;
alter table public.subscriptions alter column end_date drop default;
alter table public.trainings alter column session_date drop default;
alter table public.transactions alter column transaction_date drop default;
alter table public.matches alter column match_date drop default;
alter table public.players alter column birth_date type date using birth_date::date;
alter table public.players alter column joined_date type date using joined_date::date;
alter table public.subscriptions alter column start_date type date using start_date::date;
alter table public.subscriptions alter column end_date type date using end_date::date;
alter table public.subscriptions alter column paid_at type timestamptz using case when nullif(trim(paid_at),'') is null then null else paid_at::timestamptz end;
alter table public.matches alter column match_date type date using match_date::date;
alter table public.trainings alter column session_date type date using session_date::date;
alter table public.transactions alter column transaction_date type date using transaction_date::date;
